###Add a category
POST http://localhost:5005/cuisines/create
Content-Type: application/json

{
    "name": "Mexican",
    "avatar": "1678173221942-CanadianFood.png"
}

###Get All
GET http://localhost:5005/cuisines/list
Content-Type: application/json

###Get by id
GET http://localhost:5005/cuisines/1
Content-Type: application/json


###Edit a product
PUT http://localhost:5005/cuisines/edit/1
Content-Type: application/json

{
    "name": "Italian",
    "avatar": "1678173221942-CanadianFood.png"
}


###Delete
DELETE http://localhost:5005/cuisines/delete/1
Content-Type: application/json